version: "3.9"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    env_file:
      - .env
    networks:
      - prisma-network

networks:
  prisma-network:
    name: prisma-network
